# Generated by Django 3.1.3 on 2021-05-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders_done',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='OrdersDone',
        ),
    ]
