# Generated by Django 3.1.3 on 2021-05-15 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210515_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='orders_done',
        ),
    ]
