# Generated by Django 3.1.3 on 2021-05-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20210515_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='CooksWorkingHours',
        ),
        migrations.DeleteModel(
            name='DistributorsWorkingHours',
        ),
    ]
