# Generated by Django 3.1.3 on 2021-05-15 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphs', '0003_auto_20210515_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishesbypopularity',
            options={'verbose_name_plural': 'Dishes By Popularity'},
        ),
        migrations.AlterModelOptions(
            name='employeeworkinghours',
            options={'verbose_name_plural': 'Employee Orders Done'},
        ),
        migrations.AddField(
            model_name='employeeworkinghours',
            name='number_of_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeworkinghours',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
