# Generated by Django 3.1.3 on 2021-05-15 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20210515_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkinghours',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
