# Generated by Django 3.1.3 on 2021-05-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_employeeworkinghours_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkinghours',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='employeeworkinghours',
            name='number_of_orders',
            field=models.IntegerField(default=1),
        ),
    ]
