# Generated by Django 3.1.3 on 2021-03-04 23:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-time_added',),
            },
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.UUIDField(default=uuid.uuid4)),
                ('unconfirmed_orders', models.TextField(default='[]', null=True)),
                ('confirmed_orders', models.TextField(default='[]', null=True)),
                ('check', models.FloatField(default=0)),
                ('QR', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='menu.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=2000)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('ingredients_en', models.CharField(blank=True, max_length=2000)),
                ('quantity', models.IntegerField(default=300)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.category')),
            ],
        ),
    ]
