# Generated by Django 3.1.3 on 2020-11-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Dishes',
            new_name='Dish',
        ),
    ]
