# Generated by Django 3.1.3 on 2020-11-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201124_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='check',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
