# Generated by Django 3.1.3 on 2021-05-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20210516_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergen',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
