# Generated by Django 3.1.3 on 2020-11-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dish_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='confirmed_orders',
        ),
        migrations.AddField(
            model_name='table',
            name='confirmed_orders',
            field=models.ManyToManyField(related_name='confirmed_orders', to='menu.Dish'),
        ),
        migrations.RemoveField(
            model_name='table',
            name='unconfirmed_orders',
        ),
        migrations.AddField(
            model_name='table',
            name='unconfirmed_orders',
            field=models.ManyToManyField(related_name='unconfirmed_orders', to='menu.Dish'),
        ),
    ]
