# Generated by Django 3.1.3 on 2020-11-28 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20201127_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='QR',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.qrcode'),
            preserve_default=False,
        ),
    ]
