# Generated by Django 3.1.3 on 2020-11-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20201121_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='table',
            name='confirmed_orders',
        ),
        migrations.AddField(
            model_name='table',
            name='confirmed_orders',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='table',
            name='unconfirmed_orders',
        ),
        migrations.AddField(
            model_name='table',
            name='unconfirmed_orders',
            field=models.TextField(null=True),
        ),
    ]
