# Generated by Django 3.1.3 on 2021-05-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_allergen_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
    ]
