# Generated by Django 3.1.3 on 2021-05-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20210516_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
