# Generated by Django 3.1.3 on 2021-03-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20210225_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title_bg',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients_bg',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients_en',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_bg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_en',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
