# Generated by Django 3.1.3 on 2021-03-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20210301_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_bg',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='ingredients_bg',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='name_bg',
            new_name='name',
        ),
    ]
