# Generated by Django 3.1.3 on 2020-11-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderscooks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersCooks',
            new_name='CooksOrders',
        ),
    ]
