# Generated by Django 3.1.3 on 2020-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20201121_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders', models.TextField(null=True)),
            ],
        ),
    ]
